sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
    - 8
    - 9
    - 10
    - 12
after_success:
    - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
